### PR TITLE
Wrong optSince var name in vacation-calendar

### PR DESCRIPTION
**Pull request by benjamingauthier**
The function findEvents wasn't working, I've just changed the var name
It's now working smoothly

### CODE REVIEW

**Comment by benjamingauthier** [comment]
@googlebot I signed it!

**Comment by sqrrrl** [comment]
Thanks :)

**Comment by erickoledadevrel** [comment]
Was this change also merged into the live Apps Script that the page links to?

**Comment by benjamingauthier** [comment]
@erickoledadevrel I don't think so. How to do that ?

**Comment by erickoledadevrel** [comment]
Only Googlers have the access to make that update. I've gone ahead and done that now.

**Pull request merged**
